version: '3'

networks:
  fabric-ca:
    name: network01

services:
  ca-tls:
    container_name: ca-tls
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
    environment:
        - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=tls-ca
        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
        - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        - /tmp/hyperledger/tls-ca:/tmp/hyperledger/fabric-ca
    networks:
        - fabric-ca
    ports:
        - 7052:7052

  rca-org1:
    container_name: rca-org1
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b rca-org1-admin:rca-org1-adminpw --port 7054'
    environment:
        - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=rca-org1
        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
        - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        - /tmp/hyperledger/org1/ca:/tmp/hyperledger/fabric-ca
    networks:
        - fabric-ca
    ports:
        - 7054:7054

  rca-org2:
    container_name: rca-org2
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminpw --port 7055'

    environment:
        - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=rca-org2
        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
        - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        - /tmp/hyperledger/org2/ca:/tmp/hyperledger/fabric-ca
    networks:
        - fabric-ca
    ports:
        - 7055:7055


  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
        # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - fabric-ca

  peer1-org1:
    container_name: peer1-org1
    image: hyperledger/fabric-peer:2.3
    environment:
        - CORE_PEER_ID=peer1-org1
        - CORE_PEER_ADDRESS=peer1-org1:7051
        - CORE_PEER_LOCALMSPID=org1MSP
        - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
        - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org1/peer1/msp
        #- CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network01
        - FABRIC_LOGGING_SPEC=info
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org1/peer1/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org1/peer1/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org1/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org1:7051
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
        - CORE_PEER_ADDRESSAUTODETECT=true
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        # provide the credentials for ledger to connect to CouchDB.  The username and password must
        # match the username and password set for the associated CouchDB.
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        #- CORE_CHAINCODE_EXTERNALBUILDERS=[{name:external-sample-builder,path:/opt/gopath/src/github.com/hyperledger/fabric-samples}]
    depends_on:
      - couchdb0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer1
    volumes:
        #- /var/run:/host/var/run
        - /tmp/hyperledger/org1/peer1:/tmp/hyperledger/org1/peer1
        - /tmp/hyperledger/sampleBuilder:/opt/gopath/src/github.com/hyperledger/fabric-samples
        - /tmp/hyperledger/config/external_core.yaml:/etc/hyperledger/fabric/core.yaml
    ports:
        - 7051:7051
        - 7062:7062
    networks:
        - fabric-ca

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
        # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"
    networks:
      - fabric-ca

  peer1-org2:
    container_name: peer1-org2
    image: hyperledger/fabric-peer:2.3
    environment:
        - CORE_PEER_ID=peer1-org2
        - CORE_PEER_ADDRESS=peer1-org2:8051
        - CORE_PEER_LOCALMSPID=org2MSP
        - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
        - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2/peer1/msp
        #- CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network01
        - FABRIC_LOGGING_SPEC=DEBUG
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org2/peer1/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org2/peer1/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org2:8051
        - CORE_PEER_ADDRESSAUTODETECT=true
        - CORE_PEER_CHAINCODEADDRESS=peer1-org2:8062
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8062
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        # provide the credentials for ledger to connect to CouchDB.  The username and password must
        # match the username and password set for the associated CouchDB.
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        #- CORE_CHAINCODE_EXTERNALBUILDERS=[{name:external-sample-builder,path:/opt/gopath/src/github.com/hyperledger/fabric-samples}]
    depends_on:
      - couchdb1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer1
    volumes:
        #- /var/run:/host/var/run
        - /tmp/hyperledger/org2/peer1:/tmp/hyperledger/org2/peer1
        - /tmp/hyperledger/sampleBuilder:/opt/gopath/src/github.com/hyperledger/fabric-samples
        - /tmp/hyperledger/config/external_core.yaml:/etc/hyperledger/fabric/core.yaml
    ports:
        - 8051:8051
        - 8062:8062
    networks:
        - fabric-ca

  orderer1-org1:
    container_name: orderer1-org1
    image: hyperledger/fabric-orderer:2.3.2
    environment:
        - ORDERER_HOME=/tmp/hyperledger/orderer
        - ORDERER_HOST=orderer1-org1
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        # - ORDERER_GENERAL_GENESISMETHOD=file
        # - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/org1/orderer1/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=org1MSP
        - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/org1/orderer1/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/org1/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/org1/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/org1/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/org1/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/org1/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/org1/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
        - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7080
        - ORDERER_ADMIN_TLS_ENABLED=true
        - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/org1/orderer1/tls-msp/keystore/key.pem
        - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/org1/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
        - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/tmp/hyperledger/org1/admin/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    volumes:
        - /tmp/hyperledger/org1/orderer1:/tmp/hyperledger/org1/orderer1/
        - /tmp/hyperledger/org1/admin:/tmp/hyperledger/org1/admin/
    ports:
        - 7050:7050
        - 7080:7080
    networks:
        - fabric-ca

  orderer1-org2:
    container_name: orderer1-org2
    image: hyperledger/fabric-orderer:2.3.2
    environment:
        - ORDERER_HOME=/tmp/hyperledger/orderer
        - ORDERER_HOST=orderer1-org2
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        # - ORDERER_GENERAL_GENESISMETHOD=file
        # - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/org2/orderer1/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=org2MSP
        - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/org2/orderer1/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/org2/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/org2/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/org2/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/org2/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/org2/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/org2/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
        - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7080
        - ORDERER_ADMIN_TLS_ENABLED=true
        - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/org2/orderer1/tls-msp/keystore/key.pem
        - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/org2/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
        - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/tmp/hyperledger/org2/admin/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_CHANNELPARTICIPATION_ENABLED=true        
    volumes:
        - /tmp/hyperledger/org2/orderer1:/tmp/hyperledger/org2/orderer1/
        - /tmp/hyperledger/org2/admin:/tmp/hyperledger/org2/admin/
    ports:
        - 8050:7050
        - 8080:7080
    networks:
        - fabric-ca

  sacc-ext:
    container_name: external-sacc
    hostname: external-sacc
    image: hyperledger/sacc-ext
    environment:
        - CHAINCODE_ID=sacc-ext.0:ad9bd9625372542aab49f5218e9bc1f295482ef6e1050529061430029fb2cbd4
        - CHAINCODE_SERVER_ADDRESS=external-sacc:9998
    ports:
        - 9998:9998
    networks:
        - fabric-ca